package com;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class VaadinMainSite extends GridLayout {
    protected VerticalLayout loginVerticalLayout;
    protected Button loginButton;
    protected Button registerButton;
    protected Label mainLabelTitle;
    protected VerticalLayout searchingVerticalLayout;
    protected TextField searcherField;
    protected VerticalLayout addImageVerticalLayout;
    protected Label labelAddImage;

    public VaadinMainSite() {
        Design.read(this);
    }
}
