package com;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class VaadinRegister extends VerticalLayout {
    protected Button backButtonRegister;
    protected Label titleRegister;
    protected VerticalSplitPanel splitLineRegister;
    protected Label emailLabelRegister;
    protected TextField emailFieldRegister;
    protected Label loginLabelRegister;
    protected TextField loginFieldRegister;
    protected Label passwordLabelRegister;
    protected PasswordField passwordFieldRegister;
    protected Label repeatPasswordLabelRegister;
    protected PasswordField repeatPasswordFieldRegister;
    protected Button registerButtonInRegister;

    public VaadinRegister() {
        Design.read(this);
    }



    public TextField getLoginFieldRegister() {
        return loginFieldRegister;
    }

    public TextField getEmailFieldRegister() {
        return emailFieldRegister;
    }

    public PasswordField getPasswordFieldRegister() {
        return passwordFieldRegister;
    }

    public PasswordField getRepeatPasswordFieldRegister() {
        return repeatPasswordFieldRegister;
    }
}
