package com;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class VaadinLogin extends VerticalLayout {
    protected Button backButtonLogin;
    protected Label titleLogin;
    protected VerticalSplitPanel splitLineLogin;
    protected Label loginLabel;
    protected TextField loginField;
    protected Label passwordLabel;
    protected PasswordField passwordField;
    protected Button loginButtonInLogin;

    public VaadinLogin() {
        Design.read(this);
    }
}
